services:
  web:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    networks: [web]
    labels:
      - traefik.enable=true
      - traefik.http.routers.next.rule=Host(`web.socio.it.com`)
      - traefik.http.routers.next.entrypoints=websecure
      - traefik.http.routers.next.tls=true
      - traefik.http.routers.next.tls.certresolver=lets
      - traefik.http.services.next.loadbalancer.server.port=3000

networks:
  web:
    external: true
