import type { Metadata } from "next";
import NavWrapper from "@/components/navWrapper";
import MuiProvider from "./MuiProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MuiProvider>
          <NavWrapper/>
          {children}
        </MuiProvider>
      </body>
    </html>
  );
}
